port: $NATS_PORT

http_port: $NATS_HTTP_PORT

system_account: $NATS_SYS_ACCOUNT_ID

jetstream {
	store_dir: /etc/nats/data
    cipher: "aes"
    key: $NATS_ENCRYPTION_KEY
    limits {
        max_ack_pending: 10000
        duplicate_window: 600s
    }
}

tls {
    cert_file: "/etc/nats/certs/server.pem"
    key_file:  "/etc/nats/certs/server.key"
    ca_file:   "/etc/nats/certs/ca.pem"
}
# ca.key: chiave PRIVATA della CA(in questo caso noi)
# ca.srl: reigstro di OpenSSL per tenere traccia di quanti certificati ha firmato la ca
# server.csr: "modulo di richiesta", contiene informazioni del server, inviato alla CA per far firmare il server.pem(si può cancellare una volta ottenuto il .pem)

# ca.pem: certificato PUBBLICO della CA che garantisce se un certificato è stato veramente firmato dalla CA
# server.key: chiave SEGRETA serve per decifrare i messaggi
# server.pem: certificato finale del server firmato dalla CA

operator: /etc/nats/jwt-accounts/operator/operator.jwt

resolver: {
    type: full #tutti gli account salvati in ogni NATS server(alternativa a cache)
    dir: '/etc/nats/jwt-accounts' #cache locale degli accounts
    allow_delete: true #permette l'eliminazione dell'account ma lo rinomina con .delete in caso di errore(puliza dei .delete manuale)
}
