services:
  timescale:
    image: timescale/timescaledb:2.25.2-pg18
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - timescale-ci-data:/var/lib/postgresql/data
      - ./timescale/schema:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20

  nats:
    image: nats:2.12.5
    command: ["-config", "/etc/nats/nats.conf"]
    healthcheck:
      test: ["CMD", "nats-server", "--check", "server"]
      interval: 3s
      timeout: 3s
      retries: 10
    ports:
      - "${NATS_PORT}:${NATS_PORT}"
      - "${NATS_HTTP_PORT}:${NATS_HTTP_PORT}"
    environment:
      NATS_ENCRYPTION_KEY: ${NATS_ENCRYPTION_KEY}
      NATS_PORT: ${NATS_PORT}
      NATS_HTTP_PORT: ${NATS_HTTP_PORT}
      NATS_SYS_ACCOUNT_ID: ${NATS_SYS_ACCOUNT_ID}
      NATS_APPLICATION_CORE_ID: ${NATS_APPLICATION_CORE_ID}
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf:ro
      - ./nats/certs:/etc/nats/certs:ro
      - ./nats/jwt-accounts:/etc/nats/jwt-accounts

  nats-manager:
    image: natsio/nats-box:0.19.3
    depends_on:
      nats:
        condition: service_healthy
    volumes:
      - ./natsManager/setup-nats.sh:/setup-nats.sh:ro
      - ./natsManager/ca.pem:/ca.pem:ro
      - ./natsManager/stream_setupper.creds:/stream_setupper.creds:ro
    entrypoint: ["sh", "/setup-nats.sh"]
    environment:
      NATS_URL: nats://${NATS_HOST}:${NATS_PORT}

volumes:
  timescale-ci-data:
  nats-js-data:
